# GB28181 SIP代理服务优化配置示例
sip:
  gb28181:
    server:
      ip: ${SIP_SERVER_IP:0.0.0.0}
      port: ${SIP_SERVER_PORT:5060}
      max-devices: ${SIP_MAX_DEVICES:10000}
      device-timeout: ${SIP_DEVICE_TIMEOUT:PT5M}
      enable-tcp: ${SIP_ENABLE_TCP:true}
      enable-udp: ${SIP_ENABLE_UDP:true}
      domain: ${SIP_DOMAIN:34020000002000000001}
      server-id: ${SIP_SERVER_ID:34020000002000000001}
      server-name: ${SIP_SERVER_NAME:GB28181-Server}
    
    client:
      keep-alive-interval: ${SIP_KEEPALIVE_INTERVAL:PT1M}
      max-retries: ${SIP_MAX_RETRIES:3}
      retry-delay: ${SIP_RETRY_DELAY:PT5S}
      register-expires: ${SIP_REGISTER_EXPIRES:3600}
      client-id: ${SIP_CLIENT_ID:34020000001320000001}
      client-name: ${SIP_CLIENT_NAME:GB28181-Client}
      username: ${SIP_USERNAME:admin}
      password: ${SIP_PASSWORD:123456}
    
    performance:
      message-queue-size: ${SIP_MESSAGE_QUEUE_SIZE:1000}
      thread-pool-size: ${SIP_THREAD_POOL_SIZE:200}
      enable-metrics: ${SIP_ENABLE_METRICS:true}
      enable-async: ${SIP_ENABLE_ASYNC:true}
      batch-size: ${SIP_BATCH_SIZE:100}
      processing-timeout-ms: ${SIP_PROCESSING_TIMEOUT:5000}
      slow-query-threshold-ms: ${SIP_SLOW_QUERY_THRESHOLD:100}
    
    cache:
      device-max-size: ${SIP_DEVICE_CACHE_SIZE:50000}
      device-expire-after-write: ${SIP_DEVICE_CACHE_WRITE_EXPIRE:PT2H}
      device-expire-after-access: ${SIP_DEVICE_CACHE_ACCESS_EXPIRE:PT30M}
      subscribe-max-size: ${SIP_SUBSCRIBE_CACHE_SIZE:5000}
      subscribe-expire-after-write: ${SIP_SUBSCRIBE_CACHE_WRITE_EXPIRE:PT5M}
      subscribe-expire-after-access: ${SIP_SUBSCRIBE_CACHE_ACCESS_EXPIRE:PT2M}
      transaction-max-size: ${SIP_TRANSACTION_CACHE_SIZE:2000}
      transaction-expire-after-write: ${SIP_TRANSACTION_CACHE_EXPIRE:PT1M}
      message-max-size: ${SIP_MESSAGE_CACHE_SIZE:10000}
      message-expire-after-write: ${SIP_MESSAGE_CACHE_WRITE_EXPIRE:PT30M}
      message-expire-after-access: ${SIP_MESSAGE_CACHE_ACCESS_EXPIRE:PT15M}
      enable-stats: ${SIP_CACHE_STATS:true}

# Spring Boot Actuator配置 - 用于监控和管理
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,caches,info,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: PT1M  # 1分钟推送间隔
    distribution:
      percentiles-histogram:
        http.server.requests: true
        sip.message.processing.time: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
        sip.message.processing.time: 0.5, 0.9, 0.95, 0.99

# 日志配置
logging:
  level:
    io.github.lunasaw.sip: ${SIP_LOG_LEVEL:INFO}
    io.github.lunasaw.gbproxy: ${SIP_LOG_LEVEL:INFO}
    org.springframework.cache: ${CACHE_LOG_LEVEL:WARN}
    com.github.benmanes.caffeine: ${CAFFEINE_LOG_LEVEL:WARN}
    javax.sip: ${SIP_STACK_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"

# Spring配置
spring:
  application:
    name: gb28181-proxy
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # JMX配置（用于监控）
  jmx:
    enabled: true
  
  # 任务调度配置
  task:
    scheduling:
      pool:
        size: ${TASK_SCHEDULING_POOL_SIZE:10}
    execution:
      pool:
        core-size: ${TASK_EXECUTION_CORE_SIZE:8}
        max-size: ${TASK_EXECUTION_MAX_SIZE:16}
        queue-capacity: ${TASK_EXECUTION_QUEUE_CAPACITY:100}
        keep-alive: ${TASK_EXECUTION_KEEP_ALIVE:60s}

# 服务器配置
server:
  port: ${HTTP_SERVER_PORT:8080}
  servlet:
    context-path: /gb28181
  tomcat:
    threads:
      max: ${TOMCAT_MAX_THREADS:200}
      min-spare: ${TOMCAT_MIN_SPARE_THREADS:10}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:8192}
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}
    connection-timeout: ${TOMCAT_CONNECTION_TIMEOUT:20000}

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev

sip:
  gb28181:
    performance:
      enable-metrics: true
      thread-pool-size: 50
      message-queue-size: 500
    cache:
      device-max-size: 1000
      enable-stats: true

logging:
  level:
    io.github.lunasaw: DEBUG
    root: INFO

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod

sip:
  gb28181:
    server:
      max-devices: 50000
    performance:
      enable-metrics: true
      thread-pool-size: 400
      message-queue-size: 2000
      processing-timeout-ms: 3000
    cache:
      device-max-size: 100000
      subscribe-max-size: 10000
      transaction-max-size: 5000
      message-max-size: 20000

logging:
  level:
    io.github.lunasaw: INFO
    root: WARN
  file:
    name: /var/log/gb28181-proxy/application.log
    max-size: 100MB
    max-history: 30

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test

sip:
  gb28181:
    performance:
      enable-metrics: false
      enable-async: false
      thread-pool-size: 10
      message-queue-size: 100
    cache:
      device-max-size: 100
      enable-stats: false

logging:
  level:
    io.github.lunasaw: DEBUG
    root: DEBUG